#CFT for creating a cross account role to be used with your DivvyCloud instance. This is for the external account
#(not the local account that is running the DivvyCloud tenant)
#https://docs.divvycloud.com/docs/instance-assume-role-aws
#Alex C
#1-25-19
---
AWSTemplateFormatVersion: '2010-09-09'

Parameters: 
  TypeOfUser: 
    Type: String
    Default: Standard User
    AllowedValues: 
      - Standard User
      - Power User
    Description: Type of permissions to give
  Externalid:
    Type: String
    Description: Enter Divvy External ID
  SourceAccountId:
    Type: String
    AllowedPattern: \d{12}
    Description: Enter source account ID that will be assuming the role. A 12 digit number is expected (ex. 123456789012)

Conditions:
  AddStandardUser: !Equals [ !Ref TypeOfUser, "Standard User" ]
  AddPowerUser: !Equals [ !Ref TypeOfUser, "Power User" ]

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Join [ ":", [ 'arn:aws:iam:', !Ref SourceAccountId, root ] ]
          Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId:
                Ref: Externalid

  #Read only policy exceeds AWS limits and must be broken into two
  ReadOnlyPolicy1:
    Type: AWS::IAM::Policy
    Condition: AddStandardUser
    Properties:
      PolicyName: DivvyCloudStandardUserPolicy1
      Roles:
      - Ref: Role
      PolicyDocument:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: s3://divvvvvyyybuuucckkeett/ReadOnlyPolicy1.json

  #Read only policy exceeds AWS limits and must be broken into two. There is no significance to the breakdown
  ReadOnlyPolicy2:
    Type: AWS::IAM::Policy
    Condition: AddStandardUser
    Properties:
      PolicyName: DivvyCloudStandardUserPolicy2
      Roles:
      - Ref: Role
      PolicyDocument:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: s3://divvvvvyyybuuucckkeett/ReadOnlyPolicy2.json

  PowerUserPolicy:
    Type: AWS::IAM::Policy
    Condition: AddPowerUser
    Properties:
      PolicyName: DivvyCloud-PowerUser-Policy
      Roles:
      - Ref: Role
      PolicyDocument:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: s3://divvvvvyyybuuucckkeett/PowerUserPolicy.json

Outputs:
  RoleARNID:
    Description: Your Role ARN ID
    Value:
      Fn::GetAtt:
      - Role
      - Arn
  ExternalID:
    Description: Your External ID
    Value:
      Ref: Externalid